FROM almalinux:9
ENV Course="DevSecOps" \
    Trainer="Siva Kumar Reddy"
ARG Duration="4 months"
RUN echo "Course is: ${Course} & Trainer is: ${Trainer} & Duration is: ${Duration}"
CMD ["sleep", "300"]