# FROM almalinux:9
# RUN dnf install nginx -y
# CMD ["nginx", "-g", "daemon off;"]

FROM run:v1             # This "run:v1" image consists of almalinux as base OS and nginx installed
CMD ["nginx", "-g", "daemon off;"]